/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import java.util.Calendar;

/**
 *
 * @author Fabrizzio Ontaneda
 */
public class Diploma extends javax.swing.JFrame {

    /**
     * Creates new form Dipolma
     */
    public Diploma() {
        initComponents();
        this.setTitle("¡Felicidades!");
        lNombre.setText(Felicidades.nombre);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Calendar c = Calendar.getInstance();
        String dia = Integer.toString(c.get(Calendar.DATE));
        jDia.setText(dia);
        this.mes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lNombre = new javax.swing.JLabel();
        jMes = new javax.swing.JLabel();
        jDia = new javax.swing.JLabel();
        jAño = new javax.swing.JLabel();
        jWallPaper = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 200, 30));

        jMes.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMes.setText("Septiembre");
        getContentPane().add(jMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 40, 20));

        jDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 20, 20));

        jAño.setText("21");
        getContentPane().add(jAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 20, 20));

        jWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/diplomaR.jpg"))); // NOI18N
        getContentPane().add(jWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnMenu.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnMenu.setText("Menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 343, 600, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        Menu mn = new Menu();
        mn.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnMenuActionPerformed

    public void mes() {
        Calendar c = Calendar.getInstance();
        String mes = Integer.toString(c.get(Calendar.MONTH));
        if(mes.equals("0")){
            jMes.setText("Enero");
        }else if(mes.equals("1")){
            jMes.setText("Febrero");
        }else if(mes.equals("2")){
            jMes.setText("Marzo");
        }else if(mes.equals("3")){
            jMes.setText("Abril");
        }else if(mes.equals("4")){
            jMes.setText("Mayo");
        }else if(mes.equals("5")){
            jMes.setText("Junio");
        }else if(mes.equals("6")){
            jMes.setText("Julio");
        }else if(mes.equals("7")){
            jMes.setText("Agosto");
        }else if(mes.equals("8")){
            jMes.setText("Septiembre");
        }else if(mes.equals("9")){
            jMes.setText("Octubre");
        }else if(mes.equals("10")){
            jMes.setText("Noviembre");
        }else if(mes.equals("11")){
            jMes.setText("Diciembre");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diploma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jAño;
    private javax.swing.JLabel jDia;
    private javax.swing.JLabel jMes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jWallPaper;
    private javax.swing.JLabel lNombre;
    // End of variables declaration//GEN-END:variables
}
