/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

/**
 *
 * @author fabri
 */
public class MenuEleccion extends javax.swing.JFrame {
    public static String link="";

    /**
     * Creates new form MenuEleccion
     */
    public MenuEleccion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Ventana Seleccción");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFoto1 = new javax.swing.JButton();
        btnFoto2 = new javax.swing.JButton();
        btnFoto3 = new javax.swing.JButton();
        jWallPaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Seleccione un Avatar antes jugar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 340, 30));

        btnFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/naveEspacialBoton.png"))); // NOI18N
        btnFoto1.setText(" ");
        btnFoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoto1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 200, 200));

        btnFoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/carroBoton.png"))); // NOI18N
        btnFoto2.setText(" ");
        btnFoto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoto2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 200, 200));

        btnFoto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/extraerrestreBoton.png"))); // NOI18N
        btnFoto3.setText(" ");
        btnFoto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoto3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 200, 200));

        jWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/portadaSeleccion.jpg"))); // NOI18N
        getContentPane().add(jWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoto1ActionPerformed
        // TODO add your handling code here:
        link="src/Recursos/naveEspacialBoton.png";
        Laberinto lb=new Laberinto();
        lb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFoto1ActionPerformed

    private void btnFoto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoto2ActionPerformed
        // TODO add your handling code here:
        link="src/Recursos/carroBoton.png";
        Laberinto lb=new Laberinto();
        lb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFoto2ActionPerformed

    private void btnFoto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoto3ActionPerformed
        // TODO add your handling code here:
        link="src/Recursos/extraerrestreBoton.png";
        Laberinto lb=new Laberinto();
        lb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFoto3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoto1;
    private javax.swing.JButton btnFoto2;
    private javax.swing.JButton btnFoto3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jWallPaper;
    // End of variables declaration//GEN-END:variables
}
